# Use classic node_modules layout to ensure compatibility with Metro, Expo CLI, etc.
nodeLinker: node-modules

# Optional: makes `yarn install` fail if lockfile or node_modules are out of sync
enableImmutableInstalls: false

# Optional: speed up installs by disabling telemetry
enableTelemetry: false

# Optional: Show detailed installation logs
logFilters:
  - code: YN0013  # Skip optional dependency warnings
    level: discard